name: Keeping tabs on crystal versions
on:
  schedule:
  - cron: '0 10 1 * *'
  push:
  pull_request:
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    container:
      image: crystallang/crystal:latest

    steps:
    - uses: actions/checkout@v2
    - name: Crystal Version
      run: |
        crystal --version
    - name: Run Build
      run: |
        shards build
